<a href="https://colab.research.google.com/github/halimAhtasham/DeepLearning/blob/main/03_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Heart Disease Prediction

## Phase 3: Data Preprocessing

### Objective

Prepare the cleaned dataset for machine learning by removing duplicate
records, separating features and target, splitting the data into training
and testing sets, and applying appropriate preprocessing techniques.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# drive mount
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# path selection
PROJECT_PATH = "/content/drive/MyDrive/Machine Learning/Projects/Heart Disease Prediction"

DATASET_PATH = PROJECT_PATH + "/Dataset"
MODEL_PATH = PROJECT_PATH + "/Models"
IMAGE_PATH = PROJECT_PATH + "/Images"

In [ ]:
# load dataset
df = pd.read_csv(DATASET_PATH +"/heart.csv")

In [ ]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
df.shape

(1025, 14)

In [ ]:
df_clean = df.drop_duplicates().copy()

In [ ]:
print("Original Dataset: ", df.shape)
print("Cleanded Dataset: ", df_clean.shape)

Original Dataset:  (1025, 14)
Cleanded Dataset:  (302, 14)

In [ ]:
df_clean.duplicated().sum()

np.int64(0)

In [ ]:
X = df_clean.drop("target", axis=1)
y = df_clean["target"]

In [ ]:
print("X shape: ", X.shape)
print("y shape: ", y.shape)

X shape:  (302, 13)
y shape:  (302,)

In [ ]:
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2

In [ ]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [ ]:
print(X.columns.tolist())

['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal']

In [ ]:
y.value_counts()

target
1    164
0    138
Name: count, dtype: int64

In [ ]:
y.value_counts(normalize=True) * 100

target
1    54.304636
0    45.695364
Name: proportion, dtype: float64

#Train Test Split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [ ]:
print("X train: ", X_train.shape)
print("X test: ", X_test.shape)
print("y train: ", y_train.shape)
print("y test: ", y_test.shape)

X train:  (241, 13)
X test:  (61, 13)
y train:  (241,)
y test:  (61,)

In [ ]:
print(y_train.value_counts(normalize=True) * 100)
print(y_test.value_counts(normalize=True) * 100)

target
1    54.356846
0    45.643154
Name: proportion, dtype: float64
target
1    54.098361
0    45.901639
Name: proportion, dtype: float64

In [ ]:
X.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
dtype: object

In [ ]:
scaler = StandardScaler()

In [ ]:
X_train_scaled = scaler.fit_transform(X_train)

In [ ]:
X_test_scaled = scaler.transform(X_test)

In [ ]:
X_train_scaled = pd.DataFrame(
    X_train_scaled,
    columns = X_train.columns,
    index = X_train.index
)

X_test_scaled = pd.DataFrame(
    X_test_scaled,
    columns = X_test.columns,
    index = X_test.index
)

In [ ]:
X_train_scaled.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
158,1.421944,-1.445595,0.986493,-0.973041,5.882908,-0.398314,-1.008059,0.408240,-0.652714,0.527263,-0.697127,-0.722716,1.075838
199,-0.465841,0.691757,-0.954281,0.756507,-0.885696,-0.398314,-1.008059,-1.104705,1.532065,-0.083233,-0.697127,-0.722716,1.075838
479,0.422528,0.691757,-0.954281,-0.197726,-0.588175,-0.398314,-1.008059,-0.882213,1.532065,1.050546,-0.697127,2.132606,1.075838
460,1.644036,0.691757,0.986493,0.517949,0.118437,-0.398314,-1.008059,-0.214737,-0.652714,0.876119,-0.697127,2.132606,1.075838
169,-1.021072,-1.445595,0.016106,-1.151959,-1.629499,-0.398314,0.875214,-0.570724,-0.652714,-0.868157,-0.697127,-0.722716,-0.544643

In [ ]:
X_train_scaled.mean().round(2)

age        -0.0
sex        -0.0
cp          0.0
trestbps   -0.0
chol        0.0
fbs        -0.0
restecg    -0.0
thalach     0.0
exang      -0.0
oldpeak    -0.0
slope      -0.0
ca          0.0
thal       -0.0
dtype: float64

In [ ]:
X_train_scaled.std().round(2)

age         1.0
sex         1.0
cp          1.0
trestbps    1.0
chol        1.0
fbs         1.0
restecg     1.0
thalach     1.0
exang       1.0
oldpeak     1.0
slope       1.0
ca          1.0
thal        1.0
dtype: float64

In [ ]:
print("Missing X train: ", X_train_scaled.isnull().sum().sum())
print("Missing X test: ", X_test_scaled.isnull().sum().sum())

Missing X train:  0
Missing X test:  0

In [ ]:
import joblib
joblib.dump(
    scaler,
    MODEL_PATH + "/scaler.pkl"
)

['/content/drive/MyDrive/Machine Learning/Projects/Heart Disease Prediction/Models/scaler.pkl']